### ISSUE TITLE
Installation guide suggestion

### ISSUE THREAD

**Issue by magoowa** [korasinski/ha-netia#3]
Hello! Thank you for making this awesome integration!
However, after installation, I was getting an error through the Home Assistant config checker: no module named 'pynetia'. After digging deeper, I understood that I was missing your python package.
Thus, I think it would be nice to alter the installation guide to make it more clear for beginners (like me) and include commands for installing **pyNetia** - in my case inside a Docker container:
`docker exec -it home-assistant /bin/bash`

After logging into the container I simply installed **pyNetia** with this command:
`pip install pyNetia`

Restarted & voila - **ha-netia** started working!

Also, please consider submitting your integration to HACS as it installs flawlessly through custom repository option & more users can find out about it!

Once agaon, thank you for developing this! All the best :)

**Comment by korasinski** [comment]
Hi!
I see that this can be quite tricky because HA is installing dependencies at startup and sometimes such error pops up. 

Thank you for providing solution, I will add this to the guide later. 

Integration will be submitted to HACS soon, I wanted to have it stable before publish to some repo. :)
